project:
  type: website

website:
  title: "Biomedical Electronic Measurements"
  description: "Duke BME 253L - Fall 2025"
  site-url: "https://mlp6.github.io/Embedded-Medical-Devices/"
  
  repo-url: "https://github.com/mlp6/Embedded-Medical-Devices/"
  repo-actions: [issue]

  sidebar:
    background: "#2d63ba"
    pinned: true
    align: center
    style: docked
    search: false
    collapse-level: 2
    contents:
      - section: "Course Information"
        contents:
        - href: course-syllabus.qmd
          text: Course Syllabus
        - href: bme-lab-policies.qmd
          text: "BME Lab Policies"
        - href: https://canvas.duke.edu/courses/61472
          text: Canvas
        - href: https://edstem.org/us/courses/81250/
          text: Ed Discussion
        - href: https://canvas.duke.edu/courses/61472
          text: Gradescope
        # - text: Panopto
        - href: software-install-tutorials.qmd
          text: "Software Installation & Tutorials"
        - href: faq.qmd
          text: FAQ
      - section: "Learning Modules"
        contents:
        - href: slides/intro-circuits.qmd
          text: "Introduction to Circuits"
        - href: slides/ohm-kcl-kvl.qmd
          text: "Ohm's Law, KCL, and KVL"
        - href: slides/r_eq.qmd
          text: "Series and Parallel Resistance"
        - href: slides/circuit-analysis.qmd
          text: "Circuit Analysis Techniques"
        - href: slides/sources.qmd
          text: "Source Transformations"
        - href: slides/ecad_kicad_schematic.qmd
          text: "ECAD using KiCad: Schematic Capture"
        - href: slides/ecad_kicad_spice.qmd
          text: "ECAD using KiCad: SPICE Modeling"
        - href: slides/reactive_components.qmd
          text: "Reactive Components: Capacitors & Inductors"
        - href: slides/complex_impedance.qmd
          text: "Complex Impedance"
        - href: slides/filters.qmd
          text: "Filters"
      - section: Labs
        contents:
        - href: labs/introduction.qmd
          text: "Introduction"
        - href: labs/ohms_power.qmd
          text: "Ohm's Law and Power"
        - href: labs/kicad.qmd
          text: "KiCad: Schematic Capture & SPICE Simulation"
        - href: labs/caps_inductors_scopes.qmd
          text: "Capacitors, Inductors, and Oscilloscopes"
        - href: labs/impedance.qmd
          text: "Impedance"
        - href: labs/filters.qmd
          text: "Filters"
        - href: labs/transient_resp.qmd
          text: "Transient Response"
        - href: labs/opamps.qmd
          text: "Operational Amplifiers"
        - href: labs/transformers_diodes.qmd
          text: "Transformers and Diodes"
        - href: labs/wheatstone_temperature.qmd
          text: "Wheatstone Bridge: Temperature Measurement"
      - section: Resources
        contents:
        - href: resources/XYZs_of_Oscopes_Tektronix.pdf
          text: "XYZ of Oscilloscopes"
        - href: slides/sinusoidal_signals.qmd
          text: "Sinusoidal Signals"
        - href: resources/teaching_assistant_expectations.qmd
          text: "Teaching Assistant Expectations"
      - section: "Problem Sets"
        contents:
        - href: problem_sets/_formatting_guidelines.qmd
          text: "Formatting Guidelines"
        - href: problem_sets/ps1.qmd
          text: "Problem Set 01"
        - href: problem_sets/ps2.qmd
          text: "Problem Set 02"
        - href: problem_sets/ps3.qmd
          text: "Problem Set 03"
        - href: problem_sets/ps4.qmd
          text: "Problem Set 04"
        - href: problem_sets/ps5.qmd
          text: "Problem Set 05"
      - section: "Old Exams"
        contents:
        - href: "exams/BME153_S09_TEST1_SOLUTIONS.pdf"
          text: "Exam 1 (Spring 2009)"
        - href: "exams/BME153_S09_TEST2_SOLUTIONS.pdf"
          text: "Exam 2 (Spring 2009)"

    page-footer:
      right: 'This page is built with [Quarto](https://quarto.org/).'
      left: "&copy; Copyright 2025, Mark Palmeri"

format:
  html:
    mainfont: Atkinson Hyperlegible
    highlight-style: a11y-light
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

linkcolor: "#5D737E"
toc: true
code-copy: hover
code-link: true
code-overflow: wrap