project:
  type: website

website:
  title: "Biomedical Electronic Measurements"
  description: "Duke BME 253L - Fall 2025"
  site-url: "https://mlp6.github.io/Embedded-Medical-Devices/"
  
  repo-url: "https://github.com/mlp6/Embedded-Medical-Devices/"
  repo-actions: [issue]

  sidebar:
    background: "#2d63ba"
    pinned: true
    align: center
    style: docked
    search: false
    collapse-level: 2
    contents:
      - section: "Course Information"
        contents:
        - href: course-syllabus.qmd
          text: Course Syllabus
        - href: bme-lab-policies.qmd
          text: "BME Lab Policies"
        - href: https://canvas.duke.edu/courses/61472
          text: Canvas
        - href: https://edstem.org/us/courses/81250/
          text: Ed Discussion
        - href: https://canvas.duke.edu/courses/61472
          text: Gradescope
        # - text: Panopto
        - href: software-install-tutorials.qmd
          text: "Software Installation & Tutorials"
        - href: faq.qmd
          text: FAQ
      - section: "Learning Modules"
      - section: "Problem Sets"
        contents:
        - href: problem_sets/ProblemSetFormatGuidelines.md
          text: "Problem Set Format Guidelines"
      - section: Labs
        contents:
        - href: labs/introduction.qmd
          text: "Introduction"
        - href: labs/ohms_power.qmd
          text: "Ohm's Law and Power"
        - href: labs/caps_inductors_scopes.qmd
          text: "Capacitors, Inductors, and Oscilloscopes"
        - href: labs/impedance.qmd
          text: "Impedance"
        - href: labs/filters.qmd
          text: "Filters"
        - href: labs/transient_resp.qmd
          text: "Transient Response"
        - href: labs/opamps.qmd
          text: "Operational Amplifiers"
        - href: labs/transformers_diodes.qmd
          text: "Transformers and Diodes"
        - href: labs/wheatstone_temperature.qmd
          text: "Wheatstone Bridge: Temperature Measurement"
      - section: Resources
        contents:
        - href: resources/XYZs_of_Oscopes_Tektronix.pdf
          text: "XYZ of Oscilloscopes"
        - href: resources/teaching_assistant_expectations.qmd
          text: "Teaching Assistant Expectations"

    page-footer:
      right: 'This page is built with [Quarto](https://quarto.org/).'
      left: "&copy; Copyright 2025, Mark Palmeri"

format:
  html:
    mainfont: Atkinson Hyperlegible
    highlight-style: a11y-light
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

linkcolor: "#5D737E"
toc: true
code-copy: hover
code-link: true
code-overflow: wrap