---
title: "Biomedical Electronic Measurements"
subtitle: "BME253L (Fall 2025)"
format:
  html: default
  pdf: default
---

## Personnel

### Instructor

Dr. Mark Palmeri (`mlp6`)

* Email: [mark.palmeri@duke.edu](mailto:mark.palmeri@duke.edu)
* [Ed Discussion](https://edstem.org/us/courses/81250)
* Office Hours: Tues & Thurs, 14:30-15:30 (258 Hudson Hall Annex)

### Teaching Assistants

* Erin O'Kane (Office Hours: Thurs, 12:30-14:30, CIEMAS 2559)
* Olutoni Akintoye (Office Hours: Sat 12:00-15:00 & Sun 14:00-17:00, Wilkinson 130)

::: callout-tip
Questions that can be answered by Dr. Palmeri or a teaching assistant should be
posted on [Ed Discussion](https://edstem.org/us/courses/81250/).
:::

## Course Times & Locations

### Lecture

Monday & Wednesday, 10:05-11:20, CIEMAS 1411 (Panopto recording **not** available)

### Labs

Wednesday, 13:25-16:25, Hudson 028A (Basement)

Attendance and participation in all lab periods is required to pass this course.
Labs can only be made up with **advanced** appoval from Dr. Palmeri.  Days/times
to make up labs will be decided by your TA and Lab Instructor in advance of
missing lab.

::: callout-caution
Two unexcused lab absences will result in automatic failure of this class.
:::

::: callout-warning
No food or drink is allowed in the lab!  Failure to adhere to this policy will
have consequences on your lab grades.
:::

::: callout-important
Please review the [lab policies](bme-lab-policies.qmd) before using the lab for
the first time this semester.
:::

## Course Objectives

This course introduces students to the foundational concepts and practical
skills in electronic circuits designed for detecting biological signals.

Upon completion of this course, students should be able to:

* Perform circuit analysis using:
  * Ohm's Law
  * Kirchhoff's Voltage and Current Laws (KVL & KCL)
  * Equivalent Resistance for Series and Parallel Circuits
  * Node Voltage Analysis
  * Mesh Current Analysis
* Analysis circuits using the complex impedance of reactive capacitors and inductors.
  * Use phasors to describe amplitude and phase for reactive circuit analysis.
  * Generate and interpret Bode plots
* Analysis and design first- and second-order filters in the frequency and time domains.
* Circuit schematic capture (KiCad)
* Circuit SPICE simulation (KiCad)
* Develop skills to use common electronic bench equipment to drive and measurement electronic circuits, including:
  * Use DC and AC voltage sources.
  * Use oscilloscopes to evaluate time and frequency domain circuit response.
  * Use digitial multimeters to measure voltage, current and impedance.
  * Use function generators to generate time-varying signals to input into circuits.
* Understand ideal operational amplifiers and their use in active amplifiers, filters and comparators.
* Understand basic semiconductor physics to describe how diodes work, and use diodes for clamping and rectification.
* Work with basic digital input/output signals.

## Prerequisites

* EGR105L or equivalent experience [git, Python]

## Textbooks

* **Required**: Practical Electronics for Inventors, Paul Scherz and Simon Monk. 3rd or 4th edition
* [Lessons in Electic Circuits](http://www.ibiblio.org/kuphaldt/electricCircuits/) (Free Online)
* Fundamentals of Electrical Engineering, Giorgio Rizzoni (First Edition or Second Edition, McGraw Hill, ISBN 9780073380377)
* The Art of Electronics, Horowitz and Hill

## Learning Management System

We will be using [Canvas](https://canvas.duke.edu/courses/61472) as the learning management
system for this course.  Most resources will be linked to the course website.
All grades will be posted via Canvas/Gradescope.

[Ed Discussion](https://edstem.org/us/courses/81250) will be used for general course questions and discussion.

## Class Schedule

This class is organized in a sequence of learning modules.  Specific details
surrounding dates for assignments associated with each module will be 
updated throughout the semester in the table and calendar below.

- Resistive Circuit Analysis
  - [Introduction to Circuits](slides/intro-circuits.qmd)
  - [Ohm's Law, KCL, KVL](slides/ohm-kcl-kvl.qmd)
  - [Equivalent Resistance](slides/r_eq.qmd)
  - [Node Voltage & Mesh Current Analysis](slides/circuit-analysis.qmd)
  - [Thevenin & Norton Equivalents](slides/sources.qmd)
- KiCad
  - [Schematic Capture](slides/ecad_kicad_schematic.qmd)
  - [SPICE Simulation](slides/ecad_kicad_spice.qmd)
- Reactive Circuit Analysis
  - [Capacitors & Inductors](slides/reactive_components.qmd)
  - [Sinusoidal Signals](slides/sinusoidal_signals.qmd)
  - [Complex Impedance & Phasors](slides/complex_impedance.qmd)
- [Filters](slides/filters.qmd)
- [Transient Analysis](slides/transient_analysis.qmd)
- [Operational Amplifiers](slides/opamps.qmd)
- [Diodes](slides/diodes.qmd)
- [Temperature Measurement Circuit](labs/lab_practical.qmd)

## Attendance & Participation

Class participation in lecture is strongly encouraged.  Students are responsible
for obtaining missed lecture content from other students in the class.  All
lecture slides/presented content will be made availabe online ([Canvas](https://canvas.duke.edu/courses/61472)).
Our classroom this semester is not equipped for Panopto recording, so students
who miss lecture will be responsible for getting lecture materials from fellow
students.

Participation on [Ed Discussion](https://edstem.org/us/courses/81250/) is also encouraged, in the form of:

* Asking questions about the course material (ideally, publicly, so that others can benefit (Anonymous okay))
* Answering questions from other students
* Sharing interesting articles or resources related to the course material

## Assignments & Grading

### Grading

Fundamental knowledge will be assessed with regular problem sets and online
quizzes.  There are important
[guidelines](problem_sets/_formatting_guidelines.qmd) to follow when
submitting your problem sets electronically to Gradescope.

Lab exercises, as described above, are mandatory to pass the class.  Lab
exercises will synthesize your theoretical and analytic circuit analysis skills
with practical circuit debugging and testing.  Lab exercises will include
pre-lab exercises and post-lab submissions of data collection and analysis from
the lab exercises.

There will be three midterm exams and a final lab practical will be held during
the final exam period in the lab.  For the exams, your best 2 midterm scores
will be counted towards your final grade.

| Grade Category   | Relative Percentage   |
|:----------------|:---------------------|
| Problem Sets & Quizzes    | 20%                  |
| Labs            | 15% (pre-lab) + 15% (post-lab) = 30%         |
| Midterms        | 2 × 15% = 30%        |
| Lab Practical   | 20%                  |

: Grade Distribution

All assignment grades will be posted to Gradescope (and linked to the Canvas
gradebook) throughout the semester to track your performance.

### Course Grade

This course is not "curved" (i.e., a distribution of grades will not be
enforced), and a traditional grading scheme will be used (e.g., 90-93 = A-,
94-97 = A, 97-100 = A+).  Participation throughout the semester will influence
rounding up/down for fractional grades.

::: callout-warning
Failing the course can happen with a cummulative score $<$ 60 or more than one
unexcused lab absence.
:::

### Regrades

Any regrading requests need to be made **within one week of grades for a given
assignment being released**. You must make the request via Gradescope and
provide a description of why you feel a regrade is appropriate. Requesting a
regrade could lead to additional loss of credit when an assignment is
re-evaluated.

Some assignments will have an opportunity to be resubmitted based on grading
feedback at the discretion of Dr. Palmeri.

### Late Policy / SDAO Accomodations

Late submission windows will be available for all assignments, minus the
in-person lab sessions and the final lab practical, and should be used to
accomodate acute illness, travel, high workload from other classes and other
unforeseen circumstances.  *This late submission window can be utilized without
penalty and without prior approval.*

Students with SDAO accomodations for extended time on assignments can use this
extended late submission window for all assignments.

Any assignments submitted after the late submission window will only be accepted
for partial credit at the discretion of Dr. Palmeri or if prior approval was
sought **before the original (not extended) due date**.

## Duke Community Standard

All students are expected to adhere to all principles of the 
[Duke Community Standard](https://trinity.duke.edu/undergraduate/academic-policies/community-standard-student-conduct).
Violations of the Duke Community Standard will be referred immediately to the
Office of Student Conduct. Please do not hesitate to talk with Dr. Palmeri about
any situations involving academic honor, especially if it is ambiguous what
should be done.

## FAQ

### Can I collaborate with other students?

Engineering is inherently a collaborative field, and in this class, you are
encouraged to work collaboratively on your projects.  That being said, all of
the work that you submit must be generated by you and reflect your understanding
of the material. 

::: callout-important
All resources used in your assignment submissions that were developed by another
person or company must be properly acknowledged.
:::

### Can I use AI?

The use of artificial intelligence is a rapidly developing resource / tool in
engineering.  In software development, there are many levels of AI-assitance
available.  Such form of assistance include the
[IntelliCode](https://visualstudio.microsoft.com/services/intellicode/) tools
and [GitHub CoPilot](https://github.com/features/copilot) (free to students
through the [GitHub Education](https://github.com/education/students) program).
These tools can be leveraged to help with coding syntax.  

::: callout-caution
You are strongly cautioned to not rely on these tools for solving circuit
analysis problems, as these tools will not be available for your midterm exams
and final lab practical.  They are best used to help complete code syntax in
this class.
:::
