---
title: Software Installation and Tutorials
subtitle: "BME253L (Fall 2025)"
date: 2025-08-01
format:
  html: default
  pdf: default
---

<!-- TODO: tailor this for Arduino coding -->
## Visual Studio Code (IDE)

We will be using [Visual Studio Code](https://code.visualstudio.com/) as the IDE for all projects in this class.  In addition to installing the base program, please install the following Extensions:

* `nRF Connect for VS Code (Extension Pack)`
* `GitLens` (help with git operations / visualization)
* `C/C++` (not the extension pack, since it include `CMake Tools` that has some incompatibilities with the Zephyr build tools)
* `Cmake`
* Microsoft `IntelliCode` (assistance with C syntax)
* State diagram software (see below)
* [GitHub CoPilot](https://code.visualstudio.com/docs/copilot/overview) (AI-assisted coding)
  * Sign up for free GitHub Education Student account to get access to this extension: https://github.com/education/students
  * You will need a document to verify your student status that includes your dates of enrollment, which your DukeCard does not contain.  Instead, you can get an Enrollment Verification document through DukeHub (Academics Tab) and convert the downloaded PDF to a JPG or PNG file to upload to GitHub.
  * Install the GitHub CoPilot extension

<!-- TODO: add this -->
## KiCad

We will be using KiCad for electronic computer aided design (ECAD), including schematic capture and Simulation Program with Integrated Circuit Emphasis (SPICE) simulations.

Install KiCad on your laptop: https://www.kicad.org/

<!-- TODO: move this to a dedicated page -->
## Technical Report Preparation

Each lab exercise will have an associated technical report submitted.  These reports will be prepared and submitted using Python-based Jupyter notebooks that will be included as part of your assignment git repositories.

You will need to be able to perform the following tasks in your Jupyter notebooks:

* Read CSV text data saved from an oscilloscope.
* Generate plots

<!-- TODO: make this a dedicated page -->
If you need to install a Python environment on your laptop, then this is a good starting point: [Getting Started with Python in VS Code](https://code.visualstudio.com/docs/python/python-tutorial).

This is a good tutorial on getting started with Jupyter notebooks in VS Code: [Jupyter Notebooks in Visual Studio Code](https://code.visualstudio.com/docs/python/jupyter-support).

<!-- TODO: maybe eliminate this? -->
## What to Submit

Complete the online Gradescope "quiz" indicating completion of each of the main tasks above.
